#include <stdio.h>

int main() {
    // Nom du fichier à créer
    char html[] = "../export/1-index.html";
    
    // Ouvrir (ou créer) le fichier en mode écriture
    FILE *file = fopen(html, "w");
    
    // Vérifier si le fichier a été ouvert correctement
    if (file == NULL) {
        perror("Error opening file");
        return 1;
    }
    
    // Écrire du contenu HTML dans le fichier
    fprintf(file, "<!DOCTYPE html>\n");
    fprintf(file, "<html>\n\t<head>\n\t<title>Test HTML File</title>\n\t\t</head><body>\n");
    fprintf(file, "<h1>Hello, World!</h1>\n");
    fprintf(file, "<p>This is a test HTML file generated by a C program.</p>\n");
    fprintf(file, "</body>\n</html>\n");
    
    // Fermer le fichier
    fclose(file);
    
    printf("File '%s' created and saved successfully.\n", html);
    
    return 0;
}
